services:
  frontend:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: npm start

  # redis:
  #   image: redis:alpine
  #   container_name: redis
  #   ports:
  #     - "6379:6379"

  backend:
    container_name: backend
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    # depends_on:
    #   - redis
    # environment:
    #   - REDIS_HOST=redis
    #   - REDIS_PORT=6379
