name: Test Registry

on:
  push:
    branches:
      - "dev"
      - "main"
  pull_request:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      JFROG_ID: ${{ secrets.JFROG_ID }}
      JFROG_USERNAME: ${{ secrets.JFROG_USERNAME }}
      JFROG_EMAIL: ${{ secrets.JFROG_EMAIL }}
      JFROG_TOKEN: ${{ secrets.JFROG_TOKEN }}
    
    steps:
    - uses: actions/checkout@v1
    # - name: test_docker_oci_helm
    #   run: |
    #     echo $JFROG_TOKEN | docker login $JFROG_ID.jfrog.io --username $JFROG_USERNAME --password-stdin
    #     if docker pull $JFROG_ID.jfrog.io/docker/ubuntu:latest; then
    #       echo "Unexpected success: Image pulled successfully"
    #       exit 1
    #     else
    #       echo "Expected failure: Received HTTP 400 error, test passed."
    #       exit 0
    #     fi

    # - name: test_docker_oci_helm_dangerous
    #   run: |
    #     echo 'This is correct syntax, but its likely been taken down by the Docker team due to being malicious.'
    #     echo $JFROG_TOKEN | docker login $JFROG_ID.jfrog.io --username $JFROG_USERNAME --password-stdin
    #     if docker pull $JFROG_ID.jfrog.io/docker/linux:3.11.0-12.19; then
    #       echo "Unexpected success: Image pulled successfully"
    #       exit 1
    #     else
    #       echo "Expected failure: Received manifest error, test passed."
    #       exit 0
    #     fi

    # - name: test_npm
    #   run: |
    #     # Writes the auth token directly to .npmrc
    #     echo "//$JFROG_ID.jfrog.io/artifactory/api/npm/npm/:_authToken=$JFROG_TOKEN" >> ~/.npmrc

    #     # Sets the JFrog registry as the default
    #     npm config set registry https://$JFROG_ID.jfrog.io/artifactory/api/npm/npm/

    #     # Installs the package
    #     if npm install riot; then
    #       echo "Unexpected success: Package installed successfully"
    #       exit 1
    #     else
    #       echo "Expected failure: Package blocked, test passed."
    #       exit 0
    #     fi

    #     # Resets the registry to the default NPM registry
    #     npm config set registry https://registry.npmjs.org/

    #     # Removes the token from .npmrc after the script
    #     sed -i '' "/$JFROG_ID.jfrog.io/d" ~/.npmrc

    # - name: test_npm_dangerous
    #   run: |
    #     # Writes the auth token directly to .npmrc
    #     echo "//$JFROG_ID.jfrog.io/artifactory/api/npm/npm/:_authToken=$JFROG_TOKEN" >> ~/.npmrc

    #     # Sets the JFrog registry as the default
    #     npm config set registry https://$JFROG_ID.jfrog.io/artifactory/api/npm/npm/

    #     # Installs the package
    #     if npm install mathlive@0.103.0; then
    #       echo "Unexpected success: Package installed successfully"
    #       exit 1
    #     else
    #       echo "Expected failure: Package blocked, test passed."
    #       exit 0
    #     fi

    #     # Resets the registry to the default NPM registry
    #     npm config set registry https://registry.npmjs.org/

    #     # Removes the token from .npmrc after the script
    #     sed -i '' "/$JFROG_ID.jfrog.io/d" ~/.npmrc

    # - name: test_go
    #   run: |
    #     echo "cd ../tests/go/; go clean -modcache; go mod tidy; export GOPROXY=https://:$JFROG_TOKEN@$JFROG_ID.jfrog.io/artifactory/api/go/go-virtual; go get github.com/gin-gonic/gin@v1.10.0",
    
    # - name: test_go_dangerous
    #   run: |
    #     echo "cd ../tests/go/; go clean -modcache; go mod tidy; export GOPROXY=https://:$JFROG_TOKEN@$JFROG_ID.jfrog.io/artifactory/api/go/go-virtual; go get github.com/golang/glog@v1.0.0"

    # - name: test_python
    #   run: |
    #     echo "cd ../tests/python; chmod +x setup.sh; ./setup.sh"

    # - name: test_python_dangerous
    #   run: |
    #     echo "cd ../tests/python; chmod +x setup-dangerous.sh; ./setup-dangerous.sh"

    - name: test_ruby
      run: |
        gem source -a https://$JFROG_EMAIL:$JFROG_TOKEN@$JFROG_ID.jfrog.io/artifactory/api/gems/ruby/
        gem install bundler
    
    - name: test_ruby_dangerous
      run: |
        gem source -a https://$JFROG_EMAIL:$JFROG_TOKEN@$JFROG_ID.jfrog.io/artifactory/api/gems/ruby/
        gem install actionpack -v 5.2.0
    
    - name: test_gradle
      run: |
        echo "GRADLE_REPO_URL=https://$JFROG_ID.jfrog.io/artifactory/java JFROG_USERNAME=$JFROG_USERNAME JFROG_TOKEN=$JFROG_TOKEN JFROG_ID=$JFROG_ID.jfrog.io/artifactory chmod +x ../tests/gradle/gradlew; ../tests/gradle/gradlew --project-dir ../tests/gradle clean addDependencyAndBuild --refresh-dependencies -DrepoUrl=$GRADLE_REPO_URL -Pdependency=org.apache.mina:mina-core:2.2.4"
    
    - name: test_gradle_dangerous
      run: |
        echo "GRADLE_REPO_URL=https://$JFROG_ID.jfrog.io/artifactory/java JFROG_USERNAME=$JFROG_USERNAME JFROG_TOKEN=$JFROG_TOKEN JFROG_ID=$JFROG_ID.jfrog.io/artifactory ../tests/gradle/gradlew --project-dir ../tests/gradle clean addDependencyAndBuild --refresh-dependencies -DrepoUrl=$GRADLE_REPO_URL -Pdependency=org.apache.mina:mina-core:2.2.1"

    - name: test_maven
      run: |
        echo "MAVEN_REPO_URL=https://$JFROG_ID.jfrog.io/artifactory/java JFROG_USERNAME=$JFROG_USERNAME JFROG_TOKEN=$JFROG_TOKEN mvn clean install -U -Dbuild.cache.enabled=false -Dmaven.repo.remote=$MAVEN_REPO_URL -Ddependency=org.apache.mina:mina-core:2.2.4 -s ../tests/maven/settings.xml -f ../tests/maven/pom.xml -Ddynamic.dependency.groupId=org.apache.mina -Ddynamic.dependency.artifactId=mina-core -Ddynamic.dependency.version=2.2.4"

    - name: test_maven_dangerous
      run: |
        echo "MAVEN_REPO_URL=https://$JFROG_ID.jfrog.io/artifactory/java JFROG_USERNAME=$JFROG_USERNAME JFROG_TOKEN=$JFROG_TOKEN mvn clean install -U -Dbuild.cache.enabled=false -Dmaven.repo.remote=$MAVEN_REPO_URL -Ddependency=org.apache.mina:mina-core:2.2.4 -s ../tests/maven/settings.xml -f ../tests/maven/pom.xml -Ddynamic.dependency.groupId=org.apache.mina -Ddynamic.dependency.artifactId=mina-core -Ddynamic.dependency.version=2.2.1"

    - name: test_rust
      run: |
        echo "cd ../tests/rust/; CARGO_REGISTRIES_DEFAULT=https://$JFROG_ID.jfrog.io/artifactory/api/cargo/cargo-remote cargo add serde"

    - name: test_rust_dangerous
      run: |
        echo "cd ../tests/rust/; CARGO_REGISTRIES_DEFAULT=https://$JFROG_ID.jfrog.io/artifactory/api/cargo/cargo-remote cargo add serde-json-wasm@1.0.0"

    - name: test_terraform
      run: |
        echo "cd ../tests/terraform; chmod +x setup.sh; ./setup.sh"

    - name: test_terraform_dangerous
      run: |
        echo "cd ../tests/terraform; chmod +x setup-dangerous.sh; ./setup-dangerous.sh"

    - name: test_cocoapods
      run: |
        if curl --fail 'https://$JFROG_EMAIL:$JFROG_TOkEN@$JFROG_ID.jfrog.io/artifactory/github/Alamofire'; then
          echo "Unexpected success: Package downloaded successfully"
          exit 1
        else
          echo "Expected failure: Received HTTP 409 error, test passed."
          exit 0
        fi

    - name: test_ansible
      run: |
        echo "dotenv -e '../.env' -- bash -c 'cd ../tests/ansible; chmod +x setup.sh; ./setup.sh'"

    - name: test_bower
      run: |
        echo "dotenv -e '../.env' -- bash -c 'cd ../tests/bower; chmod +x setup.sh; ./setup.sh'"

    - name: test_debian
      run: |
        echo "cd ../tests/alpine; chmod +x setup.sh; ./setup.sh"

    - name: test_alpine
      run: |
        if curl --fail 'https://$JFROG_EMAIL:$JFROG_TOKEN@$JFROG_ID.jfrog.io/artifactory/alpine/v3.21/main/x86_64/APKINDEX.tar.gz'; then
          echo "Unexpected success: Package downloaded successfully"
          exit 1
        else
          echo "Expected failure: Received HTTP 409 error, test passed."
          exit 0
        fi

    - name: test_sbt
      run: |
        JFROG_ID=$JFROG_ID DEPENDENCY=org.apache.mina:mina-core:2.2.4 cd ../tests/sbt; sbt --no-share --batch --color=always clean update compile

    - name: test_sbt_dangerous
      run: |
        JFROG_ID=$JFROG_ID DEPENDENCY=org.apache.mina:mina-core:2.2.1 cd ../tests/sbt; sbt --no-share --batch --color=always clean update compile

    - name: test_composer
      run: |
        cd ../tests/composer; chmod +x setup.sh; ./setup.sh

    - name: test_composer_dangerous
      run: |
        cd ../tests/composer; chmod +x setup-dangerous.sh; ./setup-dangerous.sh

    - name: test_vcs
      run: |
        cd ../tests/vcs; chmod +x setup.sh; ./setup.sh

    - name: test_vcs_dangerous
      run: |
        cd ../tests/vcs; chmod +x setup-dangerous.sh; ./setup-dangerous.sh

    - name: test_chef
      run: |
        cd ../tests/chef; chmod +x setup.sh; ./setup.sh

    - name: test_generic
      run: |
        if curl --fail 'https://$JFROG_EMAIL:$JFROG_TOKEN@$JFROG_ID.jfrog.io/artifactory/github/Alamofire'; then
          echo "Unexpected success: Package downloaded successfully"
          exit 1
        else
          echo "Expected failure: Received HTTP 409 error, test passed."
          exit 0
        fi